## Import libraries

In [1]:
import csv
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import sklearn
import numpy

In [2]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


## Read in Data and drop uneccessary variables


In [4]:
df = pd.read_csv('pokemon.csv')

In [5]:
df.head()

Number        Name Type_1  Type_2  Total  HP  Attack  Defense  Sp_Atk  \
0       1   Bulbasaur  Grass  Poison    318  45      49       49      65   
1       2     Ivysaur  Grass  Poison    405  60      62       63      80   
2       3    Venusaur  Grass  Poison    525  80      82       83     100   
3       4  Charmander   Fire     NaN    309  39      52       43      60   
4       5  Charmeleon   Fire     NaN    405  58      64       58      80   

   Sp_Def  ...  Color  hasGender  Pr_Male Egg_Group_1  Egg_Group_2  \
0      65  ...  Green       True    0.875     Monster        Grass   
1      80  ...  Green       True    0.875     Monster        Grass   
2     100  ...  Green       True    0.875     Monster        Grass   
3      50  ...    Red       True    0.875     Monster       Dragon   
4      65  ...    Red       True    0.875     Monster       Dragon   

   hasMegaEvolution Height_m Weight_kg  Catch_Rate      Body_Style  
0             False     0.71       6.9          45       quadruped  
1             False     0.99      13.0          45       quadruped  
2              True     2.01     100.0          45       quadruped  
3             False     0.61       8.5          45  bipedal_tailed  
4             False     1.09      19.0          45  bipedal_tailed  

[5 rows x 23 columns]

In [6]:
print("shape of dataset :", df.shape)

shape of dataset : (721, 23)


In [7]:
df = df.drop(['Number'], axis=1) 
df = df.drop(['Name'], axis=1) 
df = df.drop(['Type_1'], axis=1)
df = df.drop(['Egg_Group_1'], axis=1)

## Remove those columns with null values

In [8]:
df.isnull().sum()

Type_2              371
Total                 0
HP                    0
Attack                0
Defense               0
Sp_Atk                0
Sp_Def                0
Speed                 0
Generation            0
isLegendary           0
Color                 0
hasGender             0
Pr_Male              77
Egg_Group_2         530
hasMegaEvolution      0
Height_m              0
Weight_kg             0
Catch_Rate            0
Body_Style            0
dtype: int64

### Check the percentage of missing vs. total values

In [9]:
530/721*100 # Egg-Group-2

73.50901525658807

In [10]:
df = df.drop(['Egg_Group_2'], axis=1)

In [11]:
371/721*100 # Type-2

51.45631067961165

In [12]:
df = df.drop(['Type_2'], axis=1)

In [13]:
df = df.drop(['Pr_Male'], axis=1)

## Change Binary Variables into 0 and 1 values

In [14]:
df.head()

Total  HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Generation  isLegendary  \
0    318  45      49       49      65      65     45           1        False   
1    405  60      62       63      80      80     60           1        False   
2    525  80      82       83     100     100     80           1        False   
3    309  39      52       43      60      50     65           1        False   
4    405  58      64       58      80      65     80           1        False   

   Color  hasGender  hasMegaEvolution  Height_m  Weight_kg  Catch_Rate  \
0  Green       True             False      0.71        6.9          45   
1  Green       True             False      0.99       13.0          45   
2  Green       True              True      2.01      100.0          45   
3    Red       True             False      0.61        8.5          45   
4    Red       True             False      1.09       19.0          45   

       Body_Style  
0       quadruped  
1       quadruped  
2       quadruped  
3  bipedal_tailed  
4  bipedal_tailed

In [15]:
df[['isLegendary', 'hasMegaEvolution','hasGender']]=df[['isLegendary', 'hasMegaEvolution','hasGender']].astype('int')

In [16]:
df.head()

Total  HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Generation  isLegendary  \
0    318  45      49       49      65      65     45           1            0   
1    405  60      62       63      80      80     60           1            0   
2    525  80      82       83     100     100     80           1            0   
3    309  39      52       43      60      50     65           1            0   
4    405  58      64       58      80      65     80           1            0   

   Color  hasGender  hasMegaEvolution  Height_m  Weight_kg  Catch_Rate  \
0  Green          1                 0      0.71        6.9          45   
1  Green          1                 0      0.99       13.0          45   
2  Green          1                 1      2.01      100.0          45   
3    Red          1                 0      0.61        8.5          45   
4    Red          1                 0      1.09       19.0          45   

       Body_Style  
0       quadruped  
1       quadruped  
2       quadruped  
3  bipedal_tailed  
4  bipedal_tailed

## Encode Categorical Variables
### I used ordinal encoding

In [17]:
from sklearn.preprocessing import OrdinalEncoder

In [18]:
ord_enc = OrdinalEncoder()
df["Body_Style"] = ord_enc.fit_transform(df[["Body_Style"]])

In [19]:
ord_enc = OrdinalEncoder()
df["Color"] = ord_enc.fit_transform(df[["Color"]])

In [20]:
df.head()

Total  HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Generation  isLegendary  \
0    318  45      49       49      65      65     45           1            0   
1    405  60      62       63      80      80     60           1            0   
2    525  80      82       83     100     100     80           1            0   
3    309  39      52       43      60      50     65           1            0   
4    405  58      64       58      80      65     80           1            0   

   Color  hasGender  hasMegaEvolution  Height_m  Weight_kg  Catch_Rate  \
0    3.0          1                 0      0.71        6.9          45   
1    3.0          1                 0      0.99       13.0          45   
2    3.0          1                 1      2.01      100.0          45   
3    7.0          1                 0      0.61        8.5          45   
4    7.0          1                 0      1.09       19.0          45   

   Body_Style  
0         9.0  
1         9.0  
2         9.0  
3         0.0  
4         0.0

## Create training and testing data sets
### Set 67% to training and 33% to testing

In [21]:
y= df.isLegendary
x = df.drop(['isLegendary'], axis=1) 

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.33)

In [23]:
y_test.shape

(238,)

## Decision Tree

In [24]:
from sklearn import tree
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

In [25]:
model_dt = DecisionTreeClassifier()
model_dt = model_dt.fit(X_train,y_train)
y_prediction_dt = model_dt.predict(X_test)

In [26]:
c_dt = confusion_matrix(y_test, y_prediction_dt)
c_dt

array([[227,   1],
       [  3,   7]])

In [27]:
cr_dt = classification_report(y_test, y_prediction_dt)
print(cr_dt)

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       228
           1       0.88      0.70      0.78        10

    accuracy                           0.98       238
   macro avg       0.93      0.85      0.88       238
weighted avg       0.98      0.98      0.98       238



In [28]:
#import six
#import sys
#sys.modules['sklearn.externals.six'] = six

In [29]:
#from sklearn.tree import export_graphviz
#from six import StringIO
#from sklearn.externals.six import StringIO  
#from IPython.display import Image  
#import pydotplus

In [30]:
#X_train.head()

In [31]:
#feature_cols = ['Total', 'HP', 'Attack', 'Defense','Sp_Atk','Sp_Def','Speed', 'Generation', 'Color', 'hasGender', 'hadMegaEvolution', 'Height_m', 'Weight_kg', 'Catch_Rate', 'Body_Style']

In [32]:
print("Accuracy:",metrics.accuracy_score(y_test, y_prediction_dt))

Accuracy: 0.9831932773109243


### 98.3% Accuracy

## SVM

In [33]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV

In [34]:
model_linear = svm.SVC(kernel='linear') # Linear Kernel
model_linear.fit(X_train, y_train)
y_prediction_svm = model_linear.predict(X_test)


In [35]:
c_svm = confusion_matrix(y_test, y_prediction_svm)
c_svm

array([[227,   1],
       [  1,   9]])

In [36]:
cr_svm = classification_report(y_test, y_prediction_svm)
print(cr_svm)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       228
           1       0.90      0.90      0.90        10

    accuracy                           0.99       238
   macro avg       0.95      0.95      0.95       238
weighted avg       0.99      0.99      0.99       238



In [37]:
print("Accuracy:",metrics.accuracy_score(y_test, y_prediction_svm))

Accuracy: 0.9915966386554622


### 99.2% Accuracy

## K-Nearest Neighbors

In [38]:
from sklearn.neighbors import KNeighborsClassifier

In [39]:
model_knn = KNeighborsClassifier()
model_knn.fit(X_train, y_train) 
y_prediction_knn = model_knn.predict(X_test)
confusion_matrix(y_test, y_prediction_knn)

array([[225,   3],
       [  1,   9]])

In [40]:
cr_knn = classification_report(y_test, y_prediction_knn)
print(cr_knn)

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       228
           1       0.75      0.90      0.82        10

    accuracy                           0.98       238
   macro avg       0.87      0.94      0.90       238
weighted avg       0.99      0.98      0.98       238



In [41]:
print("Accuracy:",metrics.accuracy_score(y_test, y_prediction_knn))

Accuracy: 0.9831932773109243


### 98.3% Accuracy